[package]
name = "GTK-Color-Scheme-Reader"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
